### PR TITLE
Migrated the project to .NET Standard

### PR DESCRIPTION
**Pull request by aivascu**
I wanted to use this lib in my .NET Core project but couldn't because it lacks the support for it.
Please consider the following changes.

- Migrated project to .NET Standard
- Upgraded reference to Dapper
- Upgraded reference for the Tests project
- Cleaned up and beautified the code
- Removed redundant files

### CODE REVIEW

**Comment by aivascu** [comment]
@dturkenk pls at least review these changes

**Comment by dturkenk** [comment]
Hi Andrei,

Sorry about the delay. I was traveling last week. I should be able to look
at them in the next few days.

Thanks for making these changes.

**Comment by dturkenk** [comment]
Looks good.

Thanks Andrei.

I'll publish up to nuget now.

**Comment by aivascu** [comment]
Thank you!

**Pull request merged**
